--- #YAML:1.0
name:               Search-OpenSearch-Engine-KSx
version:            0.03
abstract:           KinoSearch server with OpenSearch results
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Search::OpenSearch:  0.05
    SWISH::Prog::KSx:    0.08
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
